/*
 * SPDX-FileCopyrightText: 2022-2024 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_ASSETS_FILES           74
#define MMAP_ASSETS_CHECKSUM        0xF976

enum MMAP_ASSETS_LISTS {
    MMAP_ASSETS_DICE1_BMP = 0,        /*!< dice1.bmp */
    MMAP_ASSETS_DICE2_BMP = 1,        /*!< dice2.bmp */
    MMAP_ASSETS_DICE3_BMP = 2,        /*!< dice3.bmp */
    MMAP_ASSETS_DICE4_BMP = 3,        /*!< dice4.bmp */
    MMAP_ASSETS_DICE5_BMP = 4,        /*!< dice5.bmp */
    MMAP_ASSETS_DICE6_BMP = 5,        /*!< dice6.bmp */
    MMAP_ASSETS_EMOJI_FISH_JSON = 6,        /*!< Emoji_Fish.json */
    MMAP_ASSETS_ASK_JSON = 7,        /*!< ask.json */
    MMAP_ASSETS_FISH_JSON = 8,        /*!< fish.json */
    MMAP_ASSETS_LOOK_JSON = 9,        /*!< look.json */
    MMAP_ASSETS_SPEAK_JSON = 10,        /*!< speak.json */
    MMAP_ASSETS_THINK_JSON = 11,        /*!< think.json */
    MMAP_ASSETS_100_PNG = 12,        /*!< 100.png */
    MMAP_ASSETS_101_PNG = 13,        /*!< 101.png */
    MMAP_ASSETS_102_PNG = 14,        /*!< 102.png */
    MMAP_ASSETS_103_PNG = 15,        /*!< 103.png */
    MMAP_ASSETS_104_PNG = 16,        /*!< 104.png */
    MMAP_ASSETS_150_PNG = 17,        /*!< 150.png */
    MMAP_ASSETS_153_PNG = 18,        /*!< 153.png */
    MMAP_ASSETS_154_PNG = 19,        /*!< 154.png */
    MMAP_ASSETS_300_PNG = 20,        /*!< 300.png */
    MMAP_ASSETS_301_PNG = 21,        /*!< 301.png */
    MMAP_ASSETS_302_PNG = 22,        /*!< 302.png */
    MMAP_ASSETS_303_PNG = 23,        /*!< 303.png */
    MMAP_ASSETS_304_PNG = 24,        /*!< 304.png */
    MMAP_ASSETS_305_PNG = 25,        /*!< 305.png */
    MMAP_ASSETS_306_PNG = 26,        /*!< 306.png */
    MMAP_ASSETS_307_PNG = 27,        /*!< 307.png */
    MMAP_ASSETS_308_PNG = 28,        /*!< 308.png */
    MMAP_ASSETS_309_PNG = 29,        /*!< 309.png */
    MMAP_ASSETS_310_PNG = 30,        /*!< 310.png */
    MMAP_ASSETS_311_PNG = 31,        /*!< 311.png */
    MMAP_ASSETS_312_PNG = 32,        /*!< 312.png */
    MMAP_ASSETS_313_PNG = 33,        /*!< 313.png */
    MMAP_ASSETS_314_PNG = 34,        /*!< 314.png */
    MMAP_ASSETS_315_PNG = 35,        /*!< 315.png */
    MMAP_ASSETS_316_PNG = 36,        /*!< 316.png */
    MMAP_ASSETS_317_PNG = 37,        /*!< 317.png */
    MMAP_ASSETS_318_PNG = 38,        /*!< 318.png */
    MMAP_ASSETS_350_PNG = 39,        /*!< 350.png */
    MMAP_ASSETS_351_PNG = 40,        /*!< 351.png */
    MMAP_ASSETS_399_PNG = 41,        /*!< 399.png */
    MMAP_ASSETS_400_PNG = 42,        /*!< 400.png */
    MMAP_ASSETS_401_PNG = 43,        /*!< 401.png */
    MMAP_ASSETS_402_PNG = 44,        /*!< 402.png */
    MMAP_ASSETS_403_PNG = 45,        /*!< 403.png */
    MMAP_ASSETS_404_PNG = 46,        /*!< 404.png */
    MMAP_ASSETS_405_PNG = 47,        /*!< 405.png */
    MMAP_ASSETS_406_PNG = 48,        /*!< 406.png */
    MMAP_ASSETS_407_PNG = 49,        /*!< 407.png */
    MMAP_ASSETS_408_PNG = 50,        /*!< 408.png */
    MMAP_ASSETS_409_PNG = 51,        /*!< 409.png */
    MMAP_ASSETS_410_PNG = 52,        /*!< 410.png */
    MMAP_ASSETS_456_PNG = 53,        /*!< 456.png */
    MMAP_ASSETS_457_PNG = 54,        /*!< 457.png */
    MMAP_ASSETS_499_PNG = 55,        /*!< 499.png */
    MMAP_ASSETS_500_PNG = 56,        /*!< 500.png */
    MMAP_ASSETS_501_PNG = 57,        /*!< 501.png */
    MMAP_ASSETS_502_PNG = 58,        /*!< 502.png */
    MMAP_ASSETS_503_PNG = 59,        /*!< 503.png */
    MMAP_ASSETS_504_PNG = 60,        /*!< 504.png */
    MMAP_ASSETS_507_PNG = 61,        /*!< 507.png */
    MMAP_ASSETS_508_PNG = 62,        /*!< 508.png */
    MMAP_ASSETS_509_PNG = 63,        /*!< 509.png */
    MMAP_ASSETS_510_PNG = 64,        /*!< 510.png */
    MMAP_ASSETS_511_PNG = 65,        /*!< 511.png */
    MMAP_ASSETS_512_PNG = 66,        /*!< 512.png */
    MMAP_ASSETS_513_PNG = 67,        /*!< 513.png */
    MMAP_ASSETS_514_PNG = 68,        /*!< 514.png */
    MMAP_ASSETS_515_PNG = 69,        /*!< 515.png */
    MMAP_ASSETS_900_PNG = 70,        /*!< 900.png */
    MMAP_ASSETS_901_PNG = 71,        /*!< 901.png */
    MMAP_ASSETS_999_PNG = 72,        /*!< 999.png */
    MMAP_ASSETS_NAVI_52_PNG = 73,        /*!< navi_52.png */
};
