// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_COMP_PANEL2_H
#define _UI_COMP_PANEL2_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Panel2
#define UI_COMP_PANEL2_PANEL2 0
#define UI_COMP_PANEL2_WIFISTATE 1
#define UI_COMP_PANEL2_POWERSTATE 2
#define UI_COMP_PANEL2_BATTERYBOR 3
#define UI_COMP_PANEL2_TIMESTATE 4
#define UI_COMP_PANEL2_BATTERYBORDER 5
#define _UI_COMP_PANEL2_NUM 6
lv_obj_t * ui_Panel2_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
