// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_shaiziplay_screen_init(void)
{
    ui_shaiziplay = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_shaiziplay, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel4 = lv_obj_create(ui_shaiziplay);
    lv_obj_set_width(ui_Panel4, 240);
    lv_obj_set_height(ui_Panel4, 240);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_cide_canvas = lv_canvas_create(ui_Panel4);
    // lv_canvas_set_buffer(ui_cide_canvas, cbuf, CANVAS_WIDTH, CANVAS_HEIGHT, LV_IMG_CF_TRUE_COLOR);
    // lv_obj_center(ui_cide_canvas);
    lv_obj_align(ui_cide_canvas, LV_ALIGN_BOTTOM_MID, 0, 0);

    ui_shaizibut = lv_btn_create(ui_Panel4);
    lv_obj_set_width(ui_shaizibut, 100);
    lv_obj_set_height(ui_shaizibut, 50);
    lv_obj_set_x(ui_shaizibut, 0);
    lv_obj_set_y(ui_shaizibut, -70);
    lv_obj_set_align(ui_shaizibut, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_shaizibut, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_shaizibut, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_shaizibut, lv_color_hex(0xF1BA3B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_shaizibut, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_shaizibut, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_shaizibut, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_shaizibut, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_shaizibut, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_shaizibut, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_shaizibut, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // lv_obj_set_style_shadow_color(ui_shaizibut, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED);
    // lv_obj_set_style_shadow_opa(ui_shaizibut, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    // lv_obj_set_style_transform_zoom(ui_shaizibut, 240, LV_PART_MAIN | LV_STATE_PRESSED);
    //lv_obj_set_style_transform_pivot_x(ui_shaizibut, 100, LV_PART_MAIN | LV_STATE_PRESSED);
    //lv_obj_set_style_transform_pivot_y(ui_shaizibut, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_shaizitxt = lv_label_create(ui_shaizibut);
    lv_obj_set_width(ui_shaizitxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_shaizitxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_shaizitxt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_shaizitxt, "掷骰子");
    lv_obj_set_style_text_color(ui_shaizitxt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_shaizitxt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_shaizitxt, &ui_font_OPPOSansH25, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_shaizibut, ui_event_shaizibut, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_shaiziplay, ui_event_shaiziplay, LV_EVENT_ALL, NULL);
}
