// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_shaiziplay_screen_init(void)
{
    ui_shaiziplay = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_shaiziplay, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel4 = lv_obj_create(ui_shaiziplay);
    lv_obj_set_width(ui_Panel4, 240);
    lv_obj_set_height(ui_Panel4, 240);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_shaizibut = lv_btn_create(ui_Panel4);
    lv_obj_set_width(ui_shaizibut, 100);
    lv_obj_set_height(ui_shaizibut, 50);
    lv_obj_set_x(ui_shaizibut, 0);
    lv_obj_set_y(ui_shaizibut, -70);
    lv_obj_set_align(ui_shaizibut, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_shaizibut, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_shaizibut, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_shaizibut, lv_color_hex(0xF1BA3B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_shaizibut, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_shaizibut, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_shaizibut, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_shaizibut, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_shaizibut, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_shaizibut, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_shaizibut, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_shaizibut, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_shaizibut, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_transform_zoom(ui_shaizibut, 240, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_transform_pivot_x(ui_shaizibut, 100, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_transform_pivot_y(ui_shaizibut, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_shaizitxt = lv_label_create(ui_shaizibut);
    lv_obj_set_width(ui_shaizitxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_shaizitxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_shaizitxt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_shaizitxt, "掷骰子");
    lv_obj_set_style_text_color(ui_shaizitxt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_shaizitxt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_shaizitxt, &ui_font_OPPOSansH25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_shaizi1 = lv_obj_create(ui_shaiziplay);
    lv_obj_set_width(ui_shaizi1, 60);
    lv_obj_set_height(ui_shaizi1, 60);
    lv_obj_set_x(ui_shaizi1, -75);
    lv_obj_set_y(ui_shaizi1, 30);
    lv_obj_set_align(ui_shaizi1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_shaizi1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_shaizi1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_shaizi1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_shaizi1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_shaizi1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_shaizi1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_shaizi1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_shaizi1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot1 = lv_obj_create(ui_shaizi1);
    lv_obj_set_width(ui_dot1, 10);
    lv_obj_set_height(ui_dot1, 10);
    lv_obj_clear_flag(ui_dot1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dot1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot2 = lv_obj_create(ui_shaizi1);
    lv_obj_set_width(ui_dot2, 10);
    lv_obj_set_height(ui_dot2, 10);
    lv_obj_set_align(ui_dot2, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_dot2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dot2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot3 = lv_obj_create(ui_shaizi1);
    lv_obj_set_width(ui_dot3, 10);
    lv_obj_set_height(ui_dot3, 10);
    lv_obj_set_align(ui_dot3, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_dot3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dot3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot5 = lv_obj_create(ui_shaizi1);
    lv_obj_set_width(ui_dot5, 10);
    lv_obj_set_height(ui_dot5, 10);
    lv_obj_set_align(ui_dot5, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_dot5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot5, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dot5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot6 = lv_obj_create(ui_shaizi1);
    lv_obj_set_width(ui_dot6, 10);
    lv_obj_set_height(ui_dot6, 10);
    lv_obj_set_align(ui_dot6, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_dot6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot6, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dot6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot4 = lv_obj_create(ui_shaizi1);
    lv_obj_set_width(ui_dot4, 10);
    lv_obj_set_height(ui_dot4, 10);
    lv_obj_set_align(ui_dot4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_dot4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot4, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dot4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot7 = lv_obj_create(ui_shaizi1);
    lv_obj_set_width(ui_dot7, 10);
    lv_obj_set_height(ui_dot7, 10);
    lv_obj_set_align(ui_dot7, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_dot7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot7, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dot7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_shaizi2 = lv_obj_create(ui_shaiziplay);
    lv_obj_set_width(ui_shaizi2, 60);
    lv_obj_set_height(ui_shaizi2, 60);
    lv_obj_set_x(ui_shaizi2, 0);
    lv_obj_set_y(ui_shaizi2, 30);
    lv_obj_set_align(ui_shaizi2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_shaizi2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_shaizi2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_shaizi2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_shaizi2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_shaizi2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_shaizi2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_shaizi2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_shaizi2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot15 = lv_obj_create(ui_shaizi2);
    lv_obj_set_width(ui_dot15, 10);
    lv_obj_set_height(ui_dot15, 10);
    lv_obj_clear_flag(ui_dot15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot15, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dot15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot8 = lv_obj_create(ui_shaizi2);
    lv_obj_set_width(ui_dot8, 10);
    lv_obj_set_height(ui_dot8, 10);
    lv_obj_set_align(ui_dot8, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_dot8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot8, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dot8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot9 = lv_obj_create(ui_shaizi2);
    lv_obj_set_width(ui_dot9, 10);
    lv_obj_set_height(ui_dot9, 10);
    lv_obj_set_align(ui_dot9, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_dot9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot9, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dot9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot10 = lv_obj_create(ui_shaizi2);
    lv_obj_set_width(ui_dot10, 10);
    lv_obj_set_height(ui_dot10, 10);
    lv_obj_set_align(ui_dot10, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_dot10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot10, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dot10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot11 = lv_obj_create(ui_shaizi2);
    lv_obj_set_width(ui_dot11, 10);
    lv_obj_set_height(ui_dot11, 10);
    lv_obj_set_align(ui_dot11, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_dot11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot11, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dot11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot12 = lv_obj_create(ui_shaizi2);
    lv_obj_set_width(ui_dot12, 10);
    lv_obj_set_height(ui_dot12, 10);
    lv_obj_set_align(ui_dot12, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_dot12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot12, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dot12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot13 = lv_obj_create(ui_shaizi2);
    lv_obj_set_width(ui_dot13, 10);
    lv_obj_set_height(ui_dot13, 10);
    lv_obj_set_align(ui_dot13, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_dot13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot13, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dot13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_shaizi3 = lv_obj_create(ui_shaiziplay);
    lv_obj_set_width(ui_shaizi3, 60);
    lv_obj_set_height(ui_shaizi3, 60);
    lv_obj_set_x(ui_shaizi3, 75);
    lv_obj_set_y(ui_shaizi3, 30);
    lv_obj_set_align(ui_shaizi3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_shaizi3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_shaizi3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_shaizi3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_shaizi3, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_shaizi3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_shaizi3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_shaizi3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_shaizi3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot16 = lv_obj_create(ui_shaizi3);
    lv_obj_set_width(ui_dot16, 10);
    lv_obj_set_height(ui_dot16, 10);
    lv_obj_clear_flag(ui_dot16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot16, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dot16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot17 = lv_obj_create(ui_shaizi3);
    lv_obj_set_width(ui_dot17, 10);
    lv_obj_set_height(ui_dot17, 10);
    lv_obj_set_align(ui_dot17, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_dot17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot17, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dot17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot18 = lv_obj_create(ui_shaizi3);
    lv_obj_set_width(ui_dot18, 10);
    lv_obj_set_height(ui_dot18, 10);
    lv_obj_set_align(ui_dot18, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_dot18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot18, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dot18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot19 = lv_obj_create(ui_shaizi3);
    lv_obj_set_width(ui_dot19, 10);
    lv_obj_set_height(ui_dot19, 10);
    lv_obj_set_align(ui_dot19, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_dot19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot19, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dot19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot20 = lv_obj_create(ui_shaizi3);
    lv_obj_set_width(ui_dot20, 10);
    lv_obj_set_height(ui_dot20, 10);
    lv_obj_set_align(ui_dot20, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_dot20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot20, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dot20, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot21 = lv_obj_create(ui_shaizi3);
    lv_obj_set_width(ui_dot21, 10);
    lv_obj_set_height(ui_dot21, 10);
    lv_obj_set_align(ui_dot21, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_dot21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot21, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dot21, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot22 = lv_obj_create(ui_shaizi3);
    lv_obj_set_width(ui_dot22, 10);
    lv_obj_set_height(ui_dot22, 10);
    lv_obj_set_align(ui_dot22, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_dot22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot22, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dot22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);





    lv_obj_add_event_cb(ui_shaizibut, ui_event_shaizibut, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_shaiziplay, ui_event_shaiziplay, LV_EVENT_ALL, NULL);

}
