// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

#define TAG "ui"

///////////////////// VARIABLES ////////////////////
void muyushow_Animation(lv_obj_t * TargetObject, int delay);
void blink_Animation(lv_obj_t * TargetObject, int delay);
void top_Animation(lv_obj_t * TargetObject, int delay);
void weather_Animation(lv_obj_t * TargetObject, int delay);
void bottom_Animation(lv_obj_t * TargetObject, int delay);
void opaon_Animation(lv_obj_t * TargetObject, int delay);
void shaizishow_Animation(lv_obj_t * TargetObject, int delay);
void gonde_txt_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_home
void ui_home_screen_init(void);
void ui_event_home(lv_event_t * e);
lv_obj_t * ui_home;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_hour;
lv_obj_t * ui_min;
lv_obj_t * ui_date;
lv_obj_t * ui_weekday;
lv_obj_t * ui_temp;
lv_obj_t * ui_weather;
lv_obj_t * ui_colon;
lv_obj_t * ui_weathershow;

// SCREEN: ui_muyuplay
void ui_muyuplay_screen_init(void);
void ui_event_muyuplay(lv_event_t * e);
lv_obj_t * ui_muyuplay;
void ui_event_Panel3(lv_event_t * e);
lv_obj_t * ui_Panel3;
lv_obj_t * ui_muyu;
lv_obj_t * ui_gongdetxt;
lv_obj_t * ui_gongde_sum;
uint32_t gongde_sum = 0;

// SCREEN: ui_shaiziplay
void ui_shaiziplay_screen_init(void);
void ui_event_shaiziplay(lv_event_t * e);
lv_obj_t * ui_shaiziplay;
lv_obj_t * ui_Panel4;
void ui_event_shaizibut(lv_event_t * e);
lv_obj_t * ui_shaizibut;
lv_obj_t * ui_shaizitxt;
lv_obj_t * ui_cide_canvas;

// SCREEN: ui_title
void ui_title_screen_init(void);
lv_obj_t * ui_title;
lv_obj_t * title_panel;
lv_obj_t * title_wifistate;
lv_obj_t * title_powerstate;
lv_obj_t * title_batterybor;
lv_obj_t * title_timestate;
lv_obj_t * title_batterytxt;

// SCREEN:ui_fish
void ui_fish_screen_init(void);
lv_obj_t * ui_fish;
void ui_event_fish(lv_event_t *e);
lv_obj_t * ui_img_fish;

// SCREEN:ui_game_2048
void ui_game_screen_init(void);
lv_obj_t * ui_game;
lv_obj_t * ui_2048;
void ui_event_game(lv_event_t *e);

void ui_event____initial_actions0(lv_event_t * e);
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
#error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void muyushow_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 150);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_zoom);
    lv_anim_set_values(&PropertyAnimation_0, -70, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_overshoot);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_zoom);
    lv_anim_start(&PropertyAnimation_0);

}
void gonde_txt_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * opacity_anim_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    opacity_anim_user_data->target = TargetObject;

    lv_anim_t opacity_anim;
    lv_anim_init(&opacity_anim);
    lv_anim_set_time(&opacity_anim, 600);
    lv_anim_set_user_data(&opacity_anim, opacity_anim_user_data);
    lv_anim_set_custom_exec_cb(&opacity_anim, _ui_anim_callback_set_text_opacity);
    lv_anim_set_values(&opacity_anim, 255, 0);
    lv_anim_set_path_cb(&opacity_anim, lv_anim_path_linear);
    lv_anim_set_delay(&opacity_anim, delay);
    lv_anim_set_deleted_cb(&opacity_anim, _ui_anim_callback_free_user_data);
    lv_anim_start(&opacity_anim);

    ui_anim_user_data_t * position_anim_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    position_anim_user_data->target = TargetObject;

    lv_anim_t position_anim;
    lv_anim_init(&position_anim);
    lv_anim_set_time(&position_anim, 600);
    lv_anim_set_user_data(&position_anim, position_anim_user_data);
    lv_anim_set_custom_exec_cb(&position_anim, _ui_anim_callback_set_y);
    lv_anim_set_values(&position_anim, -50, -95);
    lv_anim_set_path_cb(&position_anim, lv_anim_path_linear);
    lv_anim_set_delay(&position_anim, delay);
    lv_anim_set_deleted_cb(&position_anim, _ui_anim_callback_free_user_data);
    lv_anim_start(&position_anim);
}

void blink_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 255, 100);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_in);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_opacity);
    lv_anim_start(&PropertyAnimation_0);

}
void top_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 500);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, -50, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_overshoot);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_y);
    lv_anim_start(&PropertyAnimation_0);

}
void weather_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 500);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_0, -150, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_overshoot);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_x);
    lv_anim_start(&PropertyAnimation_0);

}
void bottom_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 500);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, 100, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_overshoot);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_y);
    lv_anim_start(&PropertyAnimation_0);

}
void opaon_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 500);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_text_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_opacity);
    lv_anim_start(&PropertyAnimation_0);

}

void shaizishow_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 150);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 255, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_opacity);
    lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_home(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if (event_code == LV_EVENT_SCREEN_LOAD_START) {
        bottom_Animation(ui_hour, 0);
        bottom_Animation(ui_min, 0);
        weather_Animation(ui_weathershow, 0);
        opaon_Animation(ui_weather, 0);
        opaon_Animation(ui_temp, 0);
        opaon_Animation(ui_weekday, 0);
        opaon_Animation(ui_date, 0);
        top_Animation(title_panel, 0);
        lv_obj_set_parent(title_panel, ui_Panel1);
    }
    if (event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_muyuplay, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_muyuplay_screen_init);
    }
}
void ui_event_muyuplay(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if (event_code == LV_EVENT_SCREEN_LOAD_START) {
        lv_obj_set_parent(title_panel, ui_Panel3);
    }
    if (event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_home_screen_init);
    }
    if (event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_shaiziplay, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_shaiziplay_screen_init);
    }
}
void ui_event_Panel3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if (event_code == LV_EVENT_PRESSED) {
        muyushow_Animation(ui_muyu, 0);
        gonde_txt_Animation(ui_gongdetxt, 0);
        gongde_sum++;
        lv_label_set_text_fmt(ui_gongde_sum, "#f1c40f 今日功德: %d#", gongde_sum);
    }

}

#include "cube_dice.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"

#include "bsp/esp-bsp.h"

#define WINDOWX                 100*2
#define WINDOWY                 100*2
#define swap16(x)               (((x) << 8) | ((x) >> 8))

static uint8_t *framebuf = NULL;
static lv_timer_t *timer_tinyGL = NULL;

static esp_lcd_panel_handle_t panel_handle;

static void frame_rgb888_to_rgb565(uint8_t *rgb888, uint16_t *rgb565, int width, int height)
{
    int numPixels = width * height;
    for (int i = 0; i < numPixels; i++) {
        uint8_t r = rgb888[i * 3 + 2];
        uint8_t g = rgb888[i * 3 + 1];
        uint8_t b = rgb888[i * 3 + 0];

        uint16_t r565 = (r >> 3) & 0x1F;
        uint16_t g565 = (g >> 2) & 0x3F;
        uint16_t b565 = (b >> 3) & 0x1F;

        uint16_t rgb565Value = (r565 << 11) | (g565 << 5) | b565;
        // rgb565[i] = rgb565Value;
        rgb565[i] = swap16(rgb565Value);
    }
}

static void tinygl_win_timer_cb(lv_timer_t *tmr)
{
    cube_dice_update();
    frame_rgb888_to_rgb565(framebuf, (uint16_t *)framebuf, WINDOWX, WINDOWY);

    lv_canvas_set_buffer(ui_cide_canvas, framebuf, WINDOWX, WINDOWY, LV_IMG_CF_TRUE_COLOR);

    // int x_offset = (BSP_LCD_H_RES - WINDOWX) / 2;
    // int y_offset = (BSP_LCD_V_RES - WINDOWY) / 2;
    // esp_lcd_panel_draw_bitmap(panel_handle, 0 + x_offset, 0 + y_offset, WINDOWX + x_offset, WINDOWY + y_offset, framebuf);
}

void ui_event_shaiziplay(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if (event_code == LV_EVENT_SCREEN_LOAD_START) {
        lv_obj_set_parent(title_panel, ui_Panel4);
        ESP_LOGI(TAG, "load start");

        size_t blend_size = WINDOWX * WINDOWY * 3;
        framebuf = heap_caps_calloc(blend_size, 1, MALLOC_CAP_SPIRAM);
        assert(framebuf);
        cube_dice_init(WINDOWX, WINDOWY, framebuf);

        bsp_get_panel_handle(&panel_handle);

        timer_tinyGL = lv_timer_create(tinygl_win_timer_cb, 10, NULL);
    }

    if (event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_fish, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_fish_screen_init);
        ESP_LOGI(TAG, "load ui_fish");

        lv_timer_del(timer_tinyGL);
        timer_tinyGL = NULL;
        cube_dice_deinit();
        heap_caps_free(framebuf);
        framebuf = NULL;
    }

    if (event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_muyuplay, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_muyuplay_screen_init);
        ESP_LOGI(TAG, "load ui_muyuplay");

        lv_timer_del(timer_tinyGL);
        timer_tinyGL = NULL;

        cube_dice_deinit();
        heap_caps_free(framebuf);
        framebuf = NULL;
    }
}
void ui_event_shaizibut(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if (event_code == LV_EVENT_PRESSED) {
        shaiziblink(e);
    }
}
void ui_event_fish(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if (event_code == LV_EVENT_SCREEN_LOAD_START) {
        lv_obj_set_parent(title_panel, ui_fish);
    }
    if (event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_game, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_game_screen_init);
    }
    if (event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_shaiziplay, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_shaiziplay_screen_init);
    }
}
void ui_event_game(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if (event_code == LV_EVENT_SCREEN_LOAD_START) {
        lv_obj_set_parent(title_panel, ui_game);
    }
    if (event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_home_screen_init);
    }
    if (event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_fish, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_fish_screen_init);
    }
}
void ui_event____initial_actions0(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if (event_code == LV_EVENT_SCREEN_LOAD_START) {
        blink_Animation(ui_colon, 0);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_title_screen_init();
    ui_home_screen_init();
    ui_muyuplay_screen_init();
    ui_shaiziplay_screen_init();
    ui_fish_screen_init();
    ui_game_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_obj_add_event_cb(ui____initial_actions0, ui_event____initial_actions0, LV_EVENT_ALL, NULL);

    lv_disp_load_scr(ui____initial_actions0);
    lv_disp_load_scr(ui_home);
}
